apiVersion: v1
kind: Service
metadata:
  name: pollify-webserver-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: pollify-webserver
  type: NodePort